version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    environment:
      - SESSION_SECRET=YetAnotherProject
      - UUID_NAMESPACE=ca88cfb7-e771-4da8-817b-45b12a370c95
    container_name: app-backend
    expose:
      - "3000"
    ports:
      - "3232:3000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    networks:
      app_net:

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    container_name: app-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      app_net:

networks:
  app_net:
    driver: bridge